version: '3'

services:
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-application}
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "${MYSQL_PORT:-3306}:3306"

volumes:
  database_data:
